version: '3'

services:
  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile.prod
    image: alkxyly/laravel:prod
    container_name: laravel
    networks:
      - laranet
    
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: alkxyly/nginx:prod
    container_name: nginx   
    ports:
      - "8080:80"
    networks: 
      - laranet

networks:
  laranet:
    driver: bridge