version: '3'

services:
  laravel:
    image: alkxyly/laravel:prod
    container_name: laravel
    networks:
      - laranet
    
  nginx:
    image: alkxyly/nginx:prod
    container_name: nginx   
    ports:
      - "8080:80"
    networks: 
      - laranet

networks:
  laranet:
    driver: bridge